# Generated by Django 5.0.1 on 2024-01-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(default=18)),
                ('members_count', models.IntegerField(default=100)),
                ('min_ball', models.IntegerField(default=50)),
            ],
        ),
    ]
