# Generated by Django 4.2.5 on 2024-01-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=2000)),
                ('members_count', models.IntegerField(default=1000)),
                ('min_age', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Prize',
                'verbose_name_plural': 'Prizes',
            },
        ),
        migrations.DeleteModel(
            name='Play',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
